name             'dokku-alt'
maintainer       'Richard Lee'
maintainer_email 'rl@polydice.com'
license          'Apache 2.0'
description      'Installs/Configures dokku-alt'
long_description 'Installs/Configures dokku-alt'
version          '0.1.0'
depends          'apt'
